### ISSUE TITLE
How to edit a single item ?

### ISSUE THREAD

**Issue by vinodvinu** [dezhidki/Tommy#11]
Hi, First of all, thanks for this library. I would like to edit a single item in toml file. For example, in your toml file, how do i change  "name"  in "owner" section ?

**Comment by dezhidki** [comment]
Hey,

sorry for the late response. I hope my answer will still be relevant.

This library provides a low-level API for accessing TOML file using similar API as SimpleJSON.

Once you have your TOML file loaded, you can edit values directly:
```cs
var toml = /* Load your TOML file */;
toml["owner"]["name"] = "foo"; // Set value "foo" to "owner" section
```

Note that this omits any additional checks. This assumes `owner` either does not exist or exists and is a table. You might need to do additional checks to ensure correct types.

Unfortunately at this moment there is no more exact documentation on using this parser. At the moment you can use the [README](https://github.com/dezhidki/Tommy#readme) and [checking the source code directly](https://github.com/dezhidki/Tommy/blob/master/Tommy/Tommy.cs#L42). There is a plan for more detailed documentation once the parser is compliant with spec version 1.0.0.

**Comment by vinodvinu** [comment]
Hi @dezhidki 
Thanks for the reply. Let me try. :)
