### ISSUE TITLE
Version Compliance

### ISSUE THREAD

**Issue by pha3z** [dezhidki/Tommy#12]
I came across this lib because its listed here:
https://github.com/toml-lang/toml/wiki

It is listed as v0.5 compliant.  If it is compliant with version 1.0, it would be nice if we could get the list updated.

If it's not compliant with 1.0, what would it take to make it compliant?

**Comment by dezhidki** [comment]
Hi,

Thank you for the question! The wiki is correct, Tommy is currently is 0.5.0 compliant. I am working on updating the test suite and alongside update the code for 1.0.0 compliance.

> what would it take to make it compliant?

It requires implementing all the changes between 0.5.0 and 1.0.0. Unfortunately I haven't so far seen a simple feature diff, however here's a basic list of some things to implement

* Lifting the type restriction on arrays
* Fixing allowed characters and escape sequences to align with 1.0.0 spec
* Ensuring that `+0.0`, `-0.0` are allowed and parsed correctly
* Lifting restrictions on how many consecutive quotation marks are allowed

This is just a preliminary list. At this moment I feel it is more important to build a proper 1.0.0-compliant test suite and implement code from there. I know there is [toml-lang/compliance](https://github.com/toml-lang/compliance) but the repo appears stale and the PRs are lacking.

My current progress towards 1.0.0 is on [v1.0.0-dev](https://github.com/dezhidki/Tommy/tree/v1.0.0-dev) branch, but it is far from being done. I work on it when I have spare time, but I am of course happy to accept help!

**Comment by dezhidki** [comment]
1.0.0 compliant implementation has been merged into master with #17
