### ISSUE TITLE
Parsing creates zero-length comments for uncommented nodes

### ISSUE THREAD

**Issue by FrancisRussell** [dezhidki/Tommy#13]
I've been working on an application which uses Tommy in order to modify and existing TOML file. The newly created file has no-content comments for every entry. Though I don't have time to track this down fully, it looks like the parser may transform an absence of a comment to a zero-length string.

**Comment by dezhidki** [comment]
This should be fixed with the new 1.0.0 compliant implementation as per #17. If the issue still persists, this issue ticket will be reopened.
