### ISSUE TITLE
Different variable types in one array

### ISSUE THREAD

**Issue by lingrottin** [dezhidki/Tommy#21]
If there are some variables with different types in one array, for example, `foo=["bar",1.0,1]`, Tommy won't report this as an error. Is that a bug?

**Comment by dezhidki** [comment]
Hi!

Mixed types arrays are allowed in TOML 1.0.0 as per the [format specification](https://github.com/toml-lang/toml/blob/1.0.0/toml.md#array) and [the official ABNF syntax file](https://github.com/toml-lang/toml/blob/8eae5e1c005bc5836098505f85a7aa06568999dd/toml.abnf#L204).

Following the spec, type checking for arrays was removed from Tommy 3.0.0. Tommy 2.0.0 still has the check as it follows TOML 0.5.0 spec instead.
