### ISSUE TITLE
TomlString doesn't allow specifying initial newline after delimiter

### ISSUE THREAD

**Issue by gibbed** [dezhidki/Tommy#23]
https://toml.io/en/v1.0.0#string

> Multi-line basic strings are surrounded by three quotation marks on each side and allow newlines. **A newline immediately following the opening delimiter will be trimmed.** All other whitespace and newline characters remain intact.

> Multi-line literal strings are surrounded by three single quotes on each side and allow newlines. Like literal strings, there is no escaping whatsoever. **A newline immediately following the opening delimiter will be trimmed.** All other content between the delimiters is interpreted as-is without modification.

I'd like a way to flag TomlString so it writes that initial newline. I'm currently working around the issue by manually inserting a newline.

**Comment by dezhidki** [comment]
Added `TomlString.MultilineSkipFirstLine` prop to specify this option

**Comment by gibbed** [comment]
Thanks! Though I feel like the property's name is inverted if setting this to true enables this behavior.

**Comment by dezhidki** [comment]
If `MultilineSkipFirstLine = true`, the first line of the multiline string is skipped, i.e. the actual string is put on the next line. In that sense I daresay it works.

Nevertheless, I changed it to `MultilineTrimFirstLine` to be consistent with the wording used in docs. If `MultilineTrimFirstLine = true`, it will produce the behaviour described in the docs.

One may suggest alternative property names before I make a proper release.

**Comment by gibbed** [comment]
Okay, when you word it like that, that name does make more sense. I had taken 'line' to mean 'newline' as in the empty line, not the first line of the actual value.
