### ISSUE TITLE
Toml.WriteTo Custom Output support

### ISSUE THREAD

**Issue by oSerenity** [dezhidki/Tommy#38]
i wanna be able to output to a textbox or otherwise! please add this support or please guide me where. or how is already possible, thanks!

**Comment by dezhidki** [comment]
Hi!

Would you mind elaborating? I assume a textbox is some kind of UI form, in which case I also assume that it allows you to set its contents from a `string`. For these cases, you can write a TOML node to a [`StringWriter`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stringwriter?view=net-6.0) and then obtain a generated TOML file as a string from it.

**Comment by oSerenity** [comment]
toml.WriteTo(writer) function will make a toml file well i want to output the created data to say, richtexbox or any kind of UI string output i had to force it by writing the data to a file and then reading that data instead of just outputting the data straight where i want it. displaying the data to the user, i don't want to just read a node i want the whole table output instead

**Comment by dezhidki** [comment]
> toml.WriteTo(writer) function will make a toml file

`TomlNode.WriteTo` does not itself create a file. Instead, you can pass your own instance of `TextWriter` which you can change based on your needs. In the README, the example uses `StreamWriter`:

```cs
using(StreamWriter writer = File.CreateText("out.toml"))
{
    toml.WriteTo(writer);
    // Remember to flush the data if needed!
    writer.Flush();
}
```

In this case, `StreamWriter` is a `TextWriter` that writes to a file. You can just as well use `StringWriter` to write to a string:

```cs
var sw = new StringWriter();
toml.WriteTo(sw);
var tomlString = sw.ToString();
```

Once you have a string, you can pass it to UI or other places of interest.
You can also implement your own `TextWriter` as it is an abstract class. 

`WriteTo` already supports custom output, you simply need to tell it where to write to (file, string, custom stream, etc.) :)
