### ISSUE TITLE
TomlArray serialization extra comma

### ISSUE THREAD

**Issue by Calytic** [dezhidki/Tommy#4]
Hi again!  Again, keep up the great work!

When serializing a TomlArray, an extra comma is appended to the end of the array in some cases. 

**Expected Result**: `array = [ 1 ]`

**Actual Result**: `array = [ 1, ]`

```csharp
[TestMethod]
public void TestArrayConstruct()
{
    TomlArray tomlArray = new TomlArray();

    tomlArray.Add(new TomlInteger()
    {
        Value = 1
    });

    string expectedResult = @"array = [ 1 ]";

    var table = new TomlTable
    {
        ["array"] = tomlArray
    };

    StringBuilder sb = new StringBuilder();
    using (var sw = new StringWriter(sb))
    {
        table.ToTomlString(sw);
    }

    string actualResult = sb.ToString();

    Assert.AreEqual(expectedResult, actualResult);
}
```

**Comment by dezhidki** [comment]
Hey!

So-called trailing comma [is part of the TOML spec](https://github.com/toml-lang/toml#array), so it's perfectly fine for the serializer to generate those. 

I initially left in trailing comma for the sake of saving a few lines of code. Looking back at it, I might as well make the output a bit cleaner. I'll change the behaviour ASAP.
