### ISSUE TITLE
Is this project available as a NuGet package?

### ISSUE THREAD

**Issue by VapidLinus** [dezhidki/Tommy#7]
I would love to be able to import this package using NuGet ❤️

**Comment by dezhidki** [comment]
Thanks for the suggestion!

While I initially designed this to be a single C# file you could drop into your existing project, adding this to NuGet certainly wouldn't hurt. I'll add this library to NuGet and close the issue once it's done.

**Comment by dezhidki** [comment]
The library is finally available via [NuGet](https://www.nuget.org/packages/Tommy).
It has no dependencies and targets net35 and netstandard2 which should be more than enough for most use cases.
